package com.steglab;

import java.awt.image.BufferedImage;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import javax.imageio.ImageIO;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/image") public class ImageController{
 static final byte[] MAGIC="STEGLAB1".getBytes(StandardCharsets.US_ASCII);
 BufferedImage read(MultipartFile f)throws Exception{if(f.getSize()>50*1024*1024)throw new IllegalArgumentException("This file is larger than the 50 MB limit.");var n=f.getOriginalFilename()==null?"":f.getOriginalFilename().toLowerCase();if(!(n.endsWith(".png")||n.endsWith(".bmp")))throw new IllegalArgumentException("LSB embedding accepts PNG and BMP images.");var i=ImageIO.read(f.getInputStream());if(i==null)throw new IllegalArgumentException("We could not read this image.");return i;}
 int cap(BufferedImage i,int bits,String channels){return Math.max(0,(i.getWidth()*i.getHeight()*channels.length()*bits)/8-MAGIC.length-4);}
 @PostMapping(value="/capacity",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) Map<String,Object> capacity(@RequestPart MultipartFile file,@RequestParam(defaultValue="1")int bits,@RequestParam(defaultValue="rgb")String channels)throws Exception{var i=read(file);return Map.of("filename",file.getOriginalFilename(),"width",i.getWidth(),"height",i.getHeight(),"capacity_bytes",cap(i,bits,channels));}
 @PostMapping(value="/embed",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<byte[]> embed(@RequestPart MultipartFile file,@RequestParam String message,@RequestParam(defaultValue="1")int bits,@RequestParam(defaultValue="rgb")String channels)throws Exception{var i=read(file);var data=(new String(MAGIC,StandardCharsets.US_ASCII)+String.format("%04d",message.getBytes(StandardCharsets.UTF_8).length)+message);var raw=data.getBytes(StandardCharsets.UTF_8);if(message.getBytes(StandardCharsets.UTF_8).length>cap(i,bits,channels))throw new IllegalArgumentException("Message is too large for this image.");int pos=0,mask=(1<<bits)-1;for(int y=0;y<i.getHeight();y++)for(int x=0;x<i.getWidth();x++){int p=i.getRGB(x,y);int[] v={(p>>16)&255,(p>>8)&255,p&255,(p>>>24)&255};for(char ch:channels.toCharArray()){if(pos>=raw.length*8)break;int idx=ch=='r'?0:ch=='g'?1:ch=='b'?2:3;int bit=0;for(int k=0;k<bits;k++)bit=(bit<<1)|((raw[pos/8]>>(7-pos%8))&1);v[idx]=(v[idx]&~mask)|bit;pos+=bits;}i.setRGB(x,y,(v[3]<<24)|(v[0]<<16)|(v[1]<<8)|v[2]);}var out=new ByteArrayOutputStream();ImageIO.write(i,"png",out);return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=steglab-embedded.png").contentType(MediaType.IMAGE_PNG).body(out.toByteArray());}
}
