package com.steglab;

import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import javax.sound.sampled.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api") public class ProcessingController {
 static final byte[] IMAGE_MAGIC="STEGLAB1".getBytes(StandardCharsets.US_ASCII);
 @PostMapping(value="/image/extract",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) Map<String,Object> imageExtract(@RequestPart MultipartFile file,@RequestParam(defaultValue="1")int bits,@RequestParam(defaultValue="rgb")String channels)throws Exception{var i=javax.imageio.ImageIO.read(file.getInputStream());if(i==null)throw new IllegalArgumentException("We could not read this image.");var bitsOut=new StringBuilder();for(int y=0;y<i.getHeight();y++)for(int x=0;x<i.getWidth();x++){int p=i.getRGB(x,y);int[] v={(p>>16)&255,(p>>8)&255,p&255,(p>>>24)&255};for(char c:channels.toCharArray()){int q=v[c=='r'?0:c=='g'?1:c=='b'?2:3];bitsOut.append(String.format("%"+bits+"s",Integer.toBinaryString(q&((1<<bits)-1))).replace(' ','0'));}}byte[] raw=new byte[bitsOut.length()/8];for(int j=0;j<raw.length;j++)raw[j]=(byte)Integer.parseInt(bitsOut.substring(j*8,j*8+8),2);if(!Arrays.equals(Arrays.copyOf(raw,8),IMAGE_MAGIC))throw new IllegalArgumentException("No StegLab payload was found with these settings.");int size=Integer.parseInt(new String(raw,8,4,StandardCharsets.US_ASCII));return Map.of("message",new String(raw,12,Math.min(size,raw.length-12),StandardCharsets.UTF_8),"bytes",size);}
 @PostMapping(value="/audio/embed",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<byte[]> audioEmbed(@RequestPart MultipartFile file,@RequestParam String message)throws Exception{byte[] raw=file.getBytes();if(raw.length<44||raw[0]!='R'||raw[1]!='I'||raw[2]!='F'||raw[3]!='F')throw new IllegalArgumentException("Use an uncompressed PCM WAV file.");byte[] payload=("STEGAUD1"+String.format("%04d",message.getBytes(StandardCharsets.UTF_8).length)+message).getBytes(StandardCharsets.UTF_8);if(payload.length*8>raw.length-44)throw new IllegalArgumentException("Message is too large for this WAV.");int pos=0;for(int i=44;i<raw.length&&pos<payload.length*8;i++){raw[i]=(byte)((raw[i]&254)|((payload[pos/8]>>(7-pos%8))&1));pos++;}return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=steglab-embedded.wav").contentType(MediaType.parseMediaType("audio/wav")).body(raw);}
 @PostMapping(value="/audio/extract",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) Map<String,Object> audioExtract(@RequestPart MultipartFile file)throws Exception{byte[] raw=file.getBytes();StringBuilder b=new StringBuilder();for(int i=44;i<raw.length;i++)b.append(raw[i]&1);byte[] out=new byte[b.length()/8];for(int i=0;i<out.length;i++)out[i]=(byte)Integer.parseInt(b.substring(i*8,i*8+8),2);if(!new String(out,0,8,StandardCharsets.US_ASCII).equals("STEGAUD1"))throw new IllegalArgumentException("No StegLab audio payload was found.");int n=Integer.parseInt(new String(out,8,4,StandardCharsets.US_ASCII));return Map.of("message",new String(out,12,Math.min(n,out.length-12),StandardCharsets.UTF_8),"bytes",n);}
 @PostMapping(value="/analysis/scan",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) Map<String,Object> scan(@RequestPart MultipartFile file)throws Exception{byte[] a=file.getBytes();int[] c=new int[256];for(byte x:a)c[x&255]++;double e=0;for(int n:c)if(n>0){double q=(double)n/a.length;e-=q*(Math.log(q)/Math.log(2));}int score=e>7.8?15:0;return Map.of("filename",file.getOriginalFilename(),"size",a.length,"entropy",Math.round(e*1000)/1000.0,"score",score,"verdict",score==0?"Clean":"Suspicious","findings",List.of());}
 @PostMapping("/utilities/codec") Map<String,String> codec(@RequestBody Map<String,String> p){String v=p.getOrDefault("value","");String mode=p.getOrDefault("mode","");if(mode.equals("encode-base64"))return Map.of("value",Base64.getEncoder().encodeToString(v.getBytes(StandardCharsets.UTF_8)));if(mode.equals("decode-base64"))return Map.of("value",new String(Base64.getDecoder().decode(v),StandardCharsets.UTF_8));if(mode.equals("encode-hex"))return Map.of("value",v.getBytes(StandardCharsets.UTF_8).length==0?"":HexFormat.ofDelimiter(" ").formatHex(v.getBytes(StandardCharsets.UTF_8)));if(mode.equals("binary")){var s=new StringBuilder();for(byte x:v.getBytes(StandardCharsets.UTF_8))s.append(String.format("%8s",Integer.toBinaryString(x&255)).replace(' ','0')).append(' ');return Map.of("value",s.toString().trim());}throw new IllegalArgumentException("Unsupported conversion.");}
 @PostMapping("/utilities/entropy") Map<String,Object> entropy(@RequestBody Map<String,String> p){byte[] a=p.getOrDefault("value","").getBytes(StandardCharsets.UTF_8);int[] c=new int[256];for(byte x:a)c[x&255]++;double e=0;for(int n:c)if(n>0){double q=(double)n/a.length;e-=q*(Math.log(q)/Math.log(2));}return Map.of("bytes",a.length,"entropy",Math.round(e*10000)/10000.0);}
 @PostMapping("/reports/json") ResponseEntity<String> report(@RequestBody Map<String,Object> p){return ResponseEntity.ok().contentType(MediaType.APPLICATION_JSON).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=steglab-report.json").body(p.toString());}
}
